version: "3.8"

services:
  localstack:
    image: localstack/localstack-pro
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - DEBUG=${DEBUG-}
      - DOCKER_HOST=unix:///var/run/docker.sock
    env_file:
      - ./.env
    volumes:
      - "./localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
  jenkins:
    privileged: true
    build: ./jenkins/
    image: my_marvin/jenkins-casc
    env_file:
      - jenkins/jenkins.env
    volumes:
      - ./jenkins/my_marvin.yml:/var/jenkins_home/casc.yml
    ports:
      - "8080:8080"
  githubapp:
    build: ./githubapp
    ports:
      - "3000:3000"
    volumes:
      - ./githubapp:/app
    environment:
      NODE_ENV: production
    env_file:
      - githubapp/.env
